Flume 3046 - Kafak Sink and Source Configuration Improvements
apache/logging-flume pull request #105
Opened 2017-01-23 21:30 UTC by tmgstevens

Currently the Kafka Source sets the header for the topic. The sink reads this value, rather than the statically defined topic value. We should fix this so that you can either change the topic header that is used, or just choose to prefer the statically defined topic in the sink.

Adds configuration to Kafka Source to either disable the "topic" header, or at least configure it, and the same for the Kafka Sink,

2017-01-27 15:42 UTC, simonati requested changes
Overall it looks good, thanks for catching this issue (loop bug)!

I mostly have variable naming change requests only.

After applying the patch:
- junit tests all passed (mvn test -fae -pl flume-ng-sinks/flume-ng-kafka-sink,flume-ng-sources/flume-kafka-source) 
 - also site build created an error free flumeuserguide. yaay!!!

2017-01-27 15:42 UTC, simonati commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSinkConstants.java
> +  public static final String TOPIC_DEFAULT_HEADER_NAME = "topic";
Please rename it to DEFAULT_<< property name >> to follow convention.

2017-01-27 15:42 UTC, simonati commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSink.java
> +        eventTopic = headers.get(topicHeader);
Would you mind rephrasing it to 
```java
if (allowTopicHeader) {
    eventTopic = headers.get(topicHeader);  
    if (eventTopic == null) {
       log.debug("usage of topicheader was configured but header was not available {}", info about the event); 
       eventTopic = topic;
    }
} else {
    eventTopic = topic;
}
```

2017-01-27 15:42 UTC, simonati commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSink.java
> +  private boolean allowTopicHeader;
I think allowTopicOverride would be more self describing name.

2017-01-27 15:42 UTC, simonati commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSinkConstants.java
> +  public static final String ALLOW_TOPIC_HEADER = "allowTopicHeader";
please consider my naming comment from above (ALLOW_TOPIC_OVERRIDE)

2017-01-27 15:42 UTC, simonati commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSinkConstants.java
> +  public static final String TOPIC_DEFAULT_HEADER_NAME = "topic";
Also I think TOPIC_OVERRIDE_HEADER and DEFAULT_TOPIC_OVERRIDE_HEADER naming might be better. Would you consider changing it?

2017-01-27 15:42 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final String TOPIC_HEADER_DEFAULT = "topic";
Please use naming convention for default values by prefixing DEFAULT in the name instead of postfixing: DEFAULT_TOPIC_HEADER

2017-01-27 15:42 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final boolean SET_TOPIC_HEADER_DEFAULT = true;
DEFAULT_SET_TOPIC_HEADER like above

2017-01-27 15:42 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final String TOPIC_HEADER_CONF = "topicHeader";
You may simply use TOPIC_HEADER instead.

2017-01-27 15:42 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/test/java/org/apache/flume/source/kafka/TestKafkaSource.java
> +    Thread.sleep(500L);
What is the purpose of having Thread.sleep  between startup of source and produce? Is it really needed?

2017-01-27 15:42 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/test/java/org/apache/flume/source/kafka/TestKafkaSource.java
> +    Thread.sleep(500L);
What is the purpose of having Thread.sleep  between produce and process? Is it really needed?

2017-01-27 15:42 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/test/java/org/apache/flume/source/kafka/TestKafkaSource.java
> +  public void testTopicHeaderSetNotSet() throws InterruptedException, EventDeliveryException {
Would you mind splitting it up to 3 tests which are indeed test slightly different things?

1. header override was not configured --> expect that there is a header called `topic` and its value is `test0`
2. header override was not configured only the header name --> expect that newly created header is `customTopicHeader`<->`test0`
3. header override is disabled --> expect `topic`<->`test0` and `customTopicHeader`<->`null`

2017-02-01 08:41 UTC, tmgstevens commented on flume-ng-sources/flume-kafka-source/src/test/java/org/apache/flume/source/kafka/TestKafkaSource.java
> +    Thread.sleep(500L);
This gives time for Kafka to process the message - avoids flakiness. There is precedent in other tests for this.

2017-02-01 08:41 UTC, tmgstevens commented on flume-ng-sources/flume-kafka-source/src/test/java/org/apache/flume/source/kafka/TestKafkaSource.java
> +    Thread.sleep(500L);
This gives time for Kafka to process the message - avoids flakiness. There is precedent in other tests for this.

2017-02-01 08:41 UTC, tmgstevens commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSink.java
> +  private boolean allowTopicHeader;
Done

2017-02-01 08:43 UTC, tmgstevens commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSinkConstants.java
> +  public static final String TOPIC_DEFAULT_HEADER_NAME = "topic";
Done

2017-02-01 08:44 UTC, tmgstevens commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSinkConstants.java
> +  public static final String ALLOW_TOPIC_HEADER = "allowTopicHeader";
Done

2017-02-01 08:45 UTC, tmgstevens commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSink.java
> +        eventTopic = headers.get(topicHeader);
Done

2017-02-01 08:48 UTC, tmgstevens commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final String TOPIC_HEADER_CONF = "topicHeader";
I think that's a different setting

2017-02-03 16:19 UTC, simonati commented on flume-ng-sinks/flume-ng-kafka-sink/src/test/java/org/apache/flume/sink/kafka/TestKafkaSink.java
> +    context.put(KafkaSinkConstants.TOPIC_OVERRIDE_HEADER, "bar");
nit: this line of code is not needed

2017-02-03 16:19 UTC, simonati commented on flume-ng-sinks/flume-ng-kafka-sink/src/main/java/org/apache/flume/sink/kafka/KafkaSink.java
> +            logger.debug("{} was set to true but header {} was null. Producing to {}" +
Thanks for the updated log message. I hope this will help troubleshooters.

2017-02-03 16:19 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/test/java/org/apache/flume/source/kafka/TestKafkaSource.java
> +    Thread.sleep(500L);
As discussed offline an async call is involved so keeping this.

2017-02-03 16:19 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/test/java/org/apache/flume/source/kafka/TestKafkaSource.java
> +    Thread.sleep(500L);
As discussed offline an async call is involved so keeping this.

2017-02-03 16:19 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final String TOPIC_HEADER_CONF = "topicHeader";
Please remove the _CONF postfix.

2017-02-03 16:19 UTC, simonati commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final String TOPIC_HEADER_CONF = "topicHeader";
Isn't it similar concept to the one in Sink? If not then would you mind updating the name of the DEFAULT constant to be consistent? 
(I see that KEY_HEADER looks confusing then but I guess that can be fixed in a followup commit)

2017-02-03 16:21 UTC, simonati reviewed
Only a single naming question related to the TOPIC_HEADER_CONF

2017-02-16 08:05 UTC, tmgstevens commented on flume-ng-sinks/flume-ng-kafka-sink/src/test/java/org/apache/flume/sink/kafka/TestKafkaSink.java
> +    context.put(KafkaSinkConstants.TOPIC_OVERRIDE_HEADER, "bar");
Fixed

2017-02-16 08:05 UTC, tmgstevens commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final String TOPIC_HEADER_CONF = "topicHeader";
Fixed.

2017-02-16 08:06 UTC, tmgstevens commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final boolean SET_TOPIC_HEADER_DEFAULT = true;
Done

2017-02-16 08:07 UTC, tmgstevens commented on flume-ng-sources/flume-kafka-source/src/main/java/org/apache/flume/source/kafka/KafkaSourceConstants.java
> +  public static final String TOPIC_HEADER_DEFAULT = "topic";
Done

2017-08-08 10:04 UTC, simonati commented
Hi @tmgstevens,

Could you please retrigger TravisCI (eg change in a commit message)? It failed because of an unrelated issue which has been fixed since. 

> [ERROR] Failure executing javac, but could not parse the error:
> [ERROR] javac: invalid target release: 1.8

2017-09-12 17:15 UTC, simonati approved these changes
+1
Although with this patch preserves the erroneous behaviour in the edge-case when both a sink and source is used with the default settings it didn't break backward compatibility (which I think is more important for the non edge cases. To change this behaviour it is enough to default allowTopicOverride in KafkaSink to false).  Also it is now clear from the docs what to do to break the infinite cycle. Junit tests were passed. Time for test execution didn't increase materially so it is ok. For TestKafkaSource it took 2:07min vs 1:49min and for TestKafkaSink 42s vs 41s to pass)

Commands used for testing:
mvn test -pl flume-ng-sources/flume-kafka-source
mvn test -pl flume-ng-sinks/flume-ng-kafka-sink

2017-09-12 19:59 UTC, closed without merging