[FLUME-3133] Add a 'ipHeader' config in both tcp and udp syslog source
apache/logging-flume pull request #147
Opened 2017-07-20 09:17 UTC by lingjinjiang

When I use the syslog source, I use the "host" header to tell where the event come from.However, when change the format of syslog service, the "host" header willl be missing.

So I add a new config named "ipHeader" which looks like the "portHeader" in Multiport Syslog TCP Source.
When this config is specified, a header will be added.

For more detail: 
https://issues.apache.org/jira/browse/FLUME-3133

2017-10-29 12:50 UTC, bessbd commented
Hi @lingjinjiang ,

Thank you for the pull request!

If I'm not mistaken, this change adds new configuration options.
Can you please add the necessary modifications to [FlumeUserGuide.rst](https://github.com/apache/flume/blob/trunk/flume-ng-doc/sphinx/FlumeUserGuide.rst)?


Thank you,

Donat

2017-11-11 08:31 UTC, lingjinjiang commented
Hi @bessbd ,
Thanks for your review.
I have updated the flume user guide.

2018-08-13 11:01 UTC, szaboferee requested changes
Thanks for the contribution @lingjinjiang !
Nice pull request, I appreciate the tests and the documentation.
I have found some minor issues that need to be addressed before I could commit your change.
Let me know if you need any help.

2018-08-13 11:01 UTC, szaboferee commented on flume-ng-core/src/main/java/org/apache/flume/source/SyslogSourceConfigurationConstants.java
> +  public static final String DEFAULT_IP_HEADER = "ip";
This is only used in tests so it should be defined there and not in the production code

2018-08-13 11:01 UTC, szaboferee commented on flume-ng-core/src/test/java/org/apache/flume/source/TestMultiportSyslogTCPSource.java
> +            InetAddress.getLocalHost(), getFreePort());
this breaks as the client tries to connect to a new random port and not to the port the server is listening on.

2018-08-13 11:01 UTC, szaboferee commented on flume-ng-core/src/main/java/org/apache/flume/source/MultiportSyslogTCPSource.java
> +      SocketAddress socket = session.getRemoteAddress();
This could be checked and cast to an InetSocketAddress and then getAddress().getHostAddress() to retrieve the IP.
even better, based on a flag we could retrieve the hostname as IP addresses tend to be temporary nowadays.

2018-08-13 11:19 UTC, turcsanyip requested changes
The general logic looks good to me.
There is a test failure with the current trunk version, please fix it.
I would suggest some changes / refinements regarding the header / variable names, and in the User Guide as well (please see my inline comments).

2018-08-13 11:19 UTC, turcsanyip commented on flume-ng-core/src/main/java/org/apache/flume/source/MultiportSyslogTCPSource.java
> +            SyslogSourceConfigurationConstants.CONFIG_IP_HEADER);
The existing port header contains a _local_ port, while the new port header is the _remote_ IP, so they belong to two different network interfaces.
To make it clear, I would rename the new header to 'sourceIpHeader' or 'senderIpHeader'.

(The local IP could also be stored in a header for the case when the Flume host contains multiple network cards, and this IP would belong to the existing port header and could be called ipHeader simply.)

2018-08-13 11:19 UTC, turcsanyip commented on flume-ng-core/src/main/java/org/apache/flume/source/MultiportSyslogTCPSource.java
> +      SocketAddress socket = session.getRemoteAddress();
It is an _address_ not a _socket_, so _(***)address_ name would be better for this variable.

2018-08-13 11:19 UTC, turcsanyip commented on flume-ng-doc/sphinx/FlumeUserGuide.rst
> +ipHeader              --                If specified, the IP will be stored in the header of each event using the header name specified here. This allows for interceptors and channel selectors to cus
"the IP will be stored": please specify which IP
"incoming host": it might be better to use _source_ or _sender_ instead of incoming

2018-08-13 11:19 UTC, turcsanyip commented on flume-ng-core/src/test/java/org/apache/flume/source/TestMultiportSyslogTCPSource.java
> +            InetAddress.getLocalHost(), getFreePort());
This does not work with the current trunk version.
Please rebase the PR onto trunk and fix the test failure.

2018-08-13 12:02 UTC, majorendre commented
Hi @lingjinjiang,

Could you please help me to understand the problem this PR solves?
"However, when the syslog format is changed, the "host" header will miss."
Maybe the SyslogParser needs fixing.

Thanks,
Endre

2018-08-17 13:09 UTC, asfgit commented
Can one of the admins verify this patch?

2018-11-05 12:42 UTC, majorendre commented on flume-ng-core/src/main/java/org/apache/flume/source/MultiportSyslogTCPSource.java
> +      SocketAddress socket = session.getRemoteAddress();
@szaboferee I agree
This is how the "port" is retrieved
290:      int port = ((InetSocketAddress) session.getLocalAddress()).getPort();
This seems much safer to me.

2018-11-08 18:27 UTC, turcsanyip commented
Hi @lingjinjiang,
As there was no answer from your side, I took over the issue. Your change has been rebased onto the current trunk (as there have been a lot of changes in the meantime) and the review comments have been implemented.
For further details plase see https://github.com/apache/flume/pull/234
This PR can be closed.

2019-01-13 14:00 UTC, closed without merging