FLUME-3182 add support for SSL/TLS for syslog (tcp) sources
apache/logging-flume pull request #230
Opened 2018-10-11 15:17 UTC by szaboferee

Adding SSL/TLS support for syslog and multi port syslog sources
This change also contains some refactoring to avoid code duplication in
sources with SSL/TLS support

As SSL/TLS handling is refactored it is convinient to
add the possibility to specify enabled protocol list FLUME-3275 and
add the possibility to specify enabled cipher suite list FLUME-3276

2018-10-11 15:18 UTC, szaboferee commented
some documentation is in progress, I will update the PR with that and the review fixes later

2018-10-12 14:41 UTC, turcsanyip requested changes
Generally looks good to me. Thanks for your contribution.
Please consider my suggestions regarding method names / restructuring and eliminating duplicated code sections (see my comments inline).

2018-10-12 14:41 UTC, turcsanyip commented on flume-ng-core/src/main/java/org/apache/flume/source/SslContextAwareAbstractSource.java
> +  private String[] getEnabledProtocols(String[] enabledProtocols) {
The method name is a bit misleading because the input parameter is also 'enabled protocols'.
I would rename it to getFilteredProtocols (+ getFilteredCipherSuites).

2018-10-12 14:41 UTC, turcsanyip commented on flume-ng-core/src/main/java/org/apache/flume/source/SslContextAwareAbstractSource.java
> +  protected SSLParameters getSSLParametersWithEnabledProtocolsAndCipherSuites(
The method name is a bit complicated. On the other hand, the name of the previous method does not describe exactly what it does (following the same logic that should be getSSLParametersWithEnabledProtocolsAndCipherSuitesForContext).
So it is hard to follow what these methods do.

I would simply implement the overloaded version of getEnabledProtocols / getEnabledCipherSuites with SSLParameters input parameter and extract the filtered lists from that object.

2018-10-12 14:41 UTC, turcsanyip commented on flume-ng-sdk/src/main/java/org/apache/flume/api/NettyAvroRpcClient.java
> +  private final Set<String> excludeProtocols = new LinkedHashSet<>(Arrays.asList("SSLv3"));
I think these fields and also some logic (eg. parseList()) could moved to AbstractRPCClient.

2018-10-12 14:41 UTC, turcsanyip commented on flume-ng-core/src/test/java/org/apache/flume/source/TestMultiportSyslogTCPSource.java
> +  private List<Integer> testNPortsSSL(MultiportSyslogTCPSource source, Channel channel,
This and testNPorts methods have a lot of common code. As far as I see, testNPortsSSL contains the same code as  testNPorts with some additional logic.
Wouldn't it be possible to consolidate this code duplication?

2018-10-12 14:41 UTC, turcsanyip commented on flume-ng-core/src/main/java/org/apache/flume/source/AvroSource.java
> +      this.sslEngineSupplier = sslEngineProvider;
sslEngineProvider => sslEngineSupplier

2018-10-12 16:33 UTC, majorendre commented
It looks good to me apart from the bit of code duplication @turcsanyip mentioned.

2018-10-12 16:35 UTC, majorendre approved these changes
It looks good to me apart from the bit of code duplication @turcsanyip mentioned.

2018-10-18 11:08 UTC, turcsanyip approved these changes
It looks good to me now.
Thanks for the fixes.

2018-10-18 11:20 UTC, majorendre commented
@szaboferee  Thanks for the changes, all looks good.

2018-10-18 11:46 UTC, closed without merging